name: build-deploy-ucac4-fastapi
on: [push]
jobs:
  build-deploy-astrobase:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on mintbox
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          #password: ${{ secrets.MY_PASSWORD }}
          key: ${{ secrets.MY_PRIVATE_KEY }}
          script: |
             cd ~/my_docker/ucac4-fastapi
             git pull
             docker build -t ucac4-fastapi:latest .
             cd $HOME/shared
             docker-compose -p dockernest up -d
